apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s4claw-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s4claw-operator
subjects:
  - kind: ServiceAccount
    name: k8s4claw-operator
    namespace: k8s4claw-system
